apiVersion: skaffold/v2alpha3
kind: config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: patrickgorman/inventory
      context: inventory
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
#    - image: patrickgorman/machines
#      context: machines
#      docker:
#        dockerfile: Dockerfile
#      sync:
#        manual:
#          - src: 'src/**/*.js'
#            dest: .
#    - image: patrickgorman/processes
#      context: processes
#      docker:
#        dockerfile: Dockerfile
#      sync:
#        manual:
#          - src: 'src/**/*.js'
#            dest: .
#    - image: patrickgorman/products
#      context: products
#      docker:
#        dockerfile: Dockerfile
#      sync:
#        manual:
#          - src: 'src/**/*.ts'
#            dest: .
#    - image: patrickgorman/factories
#      context: factories
#      docker:
#        dockerfile: Dockerfile
#      sync:
#        manual:
#          - src: 'src/**/*.js'
#            dest: .