apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
    spec:
      containers:
        - name: inventory
          image: patrickgorman/inventory
          env:
            - name: MONGO_URI
              value: 'mongodb://inventory-mongo-srv:27017/tickets'
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-srv
spec:
  selector:
    app: inventory
  ports:
    - name: inventory
      protocol: TCP
      port: 3000
      targetPort: 3000