name: deploy-materials

on:
  push:
    branches: [ main ]
    paths:
      - 'materials/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd machines && docker build -t ${{ secrets.DOCKER_USERNAME }}/materials .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_TOKEN }}
      - run: docker push patrickgorman/materials

