name: deploy-manifests

on:
  push:
    branches: [ main ]
    paths:
      - 'infra/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: digitialocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save kalaaiv2
      - run: kubectl apply -f infra/k8s && kubectl apply -f infra/k8s-prod

