name: deploy-materials

on:
  push:
    branches: [ main ]
#     paths:
#       - 'materials/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd materials && docker build -t patrickgorman/materials .
      - name: Login Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}       
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx 
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        id: docker_build
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/materials
      - name: Verify
        run: echo ${{ steps.docker_build.outputs.digest }}
