name: deploy-machines

on:
  push:
    branches: [ main ]
    paths:
      - 'machines/**'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd machines && docker build -t ${{ DOCKER_USERNAME }}/machines .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_TOKEN }}        
      - run: docker push patrickgorman/machines
