name: deploy-machines

on:
  push:
    branches: [ main ]
    paths:
      - 'materials/**'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd machines && docker build -t patrickgorman/machines .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}        
      - run: docker push patrickgorman/machines
