name: deploy-materials

on:
  push:
    branches: [ main ]
    paths:
      - 'materials/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd materials && docker build -t ${{ secrets.DOCKER_USERNAME }}/materials .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_TOKEN }}
      - run: docker push patrickgorman/materials
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save kalaaiv2
      - run: kubectl rollout restart deployment materials-depl

