name: Test-Factories

on:
  push:
    branches: [ main ]
    paths:
      - 'factories/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'factories/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd factories && npm install && npm run test:ci
