name: Test-Inventory

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd inventory && npm install && npm run test:ci
