name: Test-Machines

on:
  push:
    branches: [ main ]
    paths:
      - 'machines/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'machines/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd machines && npm install && npm run test:ci
