name: Test-Sales

on:
  push:
    branches: [ main ]
    paths:
      - 'products/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'products/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd sales && npm install && npm run test:ci
